### ISSUE TITLE
Diesel

### ISSUE THREAD

**Issue by digeratus** [vishusandy/rocket-auth-login#1]
Do you by any chance have a version of the database example using Diesel?
Thanks

**Comment by vishusandy** [comment]
Unfortunately I do not, I had some trouble getting Diesel to work last time I tried using it.  But I have not tried recently.  Anyways the only code you would have to change is in the authenticate() method. When you implement authenticate() instead of using the postgresql query use Diesel.

**Comment by digeratus** [comment]
Got it. Thanks. I’ll take a look. 

Thanks
