### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by kw217** [vishusandy/rocket-auth-login#6]
Hi - is there any chance you could make a new release to crates.io? The latest available there is 0.2.3, which doesn't build with current Rocket.

Thanks.

**Comment by TanguyDelume** [comment]
The version on crates.io is outdated and not working unfortunately, but it can be forced with the one from this repository (0.3.0) manually:
In cargo.toml:

```
[dependencies]
rocket-auth-login = { version = "0.3.0", git = "https://github.com/vishusandy/rocket-auth-login" }
```

**Comment by TanguyDelume** [comment]
The version on crates.io is outdated and not working unfortunately, but it can be forced with the one from this repository (0.3.0) manually, In cargo.toml:

```
[dependencies]
rocket-auth-login = { version = "0.3.0", git = "https://github.com/vishusandy/rocket-auth-login" }
```

**Comment by kw217** [comment]
Thanks.
